import Head from "next/head";

const ApaceHead = () => {
  return (
    <Head>
      <title>Apace</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/apace-fav.svg" />
    </Head>
  );
};

export default ApaceHead;
